version: '3'
services:
  mongodb:
    container_name: "mongodb"
    image: mongo:5
    ports:
      - 27017:27017
    volumes: 
     - mongodb:/data/db/
     - mongodb_config:/data/configdb
  redis:
    image: redis:6.2.6-alpine
    ports:
      -  6379:6379 
    volumes:
    - redis:/data/
volumes:
  mongodb:
  mongodb_config:
  redis: